# Channel name (used in placeholders)
name: 'Default'
# Channel operation mode
# DEFAULT - standard operation mode (simply teleports to random coordinates)
# NEAR_PLAYER - teleports the player near other players (simply put /rtp player)
# NEAR_REGION - teleports the player near a worldguard region (simply put /rtp base)
type: DEFAULT
# Worlds in which the channel is active
# If a player teleports via this channel in one of these worlds - the teleport will be in that world
active_worlds:
  - 'world'
  - 'world_nether'
  - 'world_the_end'
# Should the channel teleport the player to the world that will be first in the active_worlds list
# if the player tries to teleport through it from another world? (useful if the channel should be called from the spawn world for example)
teleport_to_first_world: true
# Which server in the network will the channel move to if proxy mode is enabled
# Names are taken from the proxy configuration, but the main plugin config must also have correct names!
# If '' is specified or proxy mode is not enabled - this will have no effect
server_to_move: ''
# How many players should be on the server to teleport via this channel? (-1 to disable)
min_players_to_use: -1
# How many ticks should the player be invulnerable after teleportation via RTP channel (-1 to disable)
invulnerable_after_teleport: 12
# Which template will be used for further channel settings? (Specified in templates.yml)
# Used if any setting is not specified directly in the channel, but should be present in it
# If '' is specified - this will have no effect
template: ''
# Channel-specific specifications
specifications:
  # Should the player be teleported to RTP on first join?
  teleport_on_first_join: false
  # From which worlds should RTP teleportation from void work.
  # Useful if you need teleportation after falling into a pit
  # If [] is specified - will not teleport when falling into void
  void_worlds: []
  # Void level. If the player descends to this height and void_worlds is not empty - they will be teleported.
  # If not specified - vanilla void level value for your version is used. (0/-60)
  void_level: 0
  # From which worlds should RTP teleportation on respawn work.
  # Works the same way as void_worlds
  respawn_worlds: []
# Teleportation cost settings for this channel
costs:
  # Currency type used
  # VAULT - vault api will be used (assumes an economy manager like EssentialsX or CMI)
  # PLAYERPOINTS - PlayerPoints plugin api will be used
  money_type: VAULT
  # Teleportation cost in coins (-1 to disable)
  money_cost: -1
  # Teleportation cost in hunger units
  hunger_cost: -1
  # Teleportation cost in experience points
  experience_cost: -1
# Location selection principle
location_generation_options:
  # Shape template for location search
  # SQUARE - rectangle. min_x/z and max_x/z are 2 opposite sides of the rectangle
  # ROUND - circle. min_x/z and max_x/z are 2 opposite sides of a rectangle through which a circle (or oval) will be built, inscribed in this rectangle
  shape: SQUARE
  # Location generation format
  # RECTANGULAR - we build one geometric figure for location generation (figure is built between max_x/z and min_x/z depending on shape)
  # RADIAL - two geometric figures are built, between which a teleportation zone is created (figures are built with maximum max_x/z and minimum min_x/z radii from center_x/z)
  gen_format: RECTANGULAR
  # Coordinates
  min_x: -1000
  max_x: 1000
  min_z: -1000
  max_z: 1000
  # Coordinates when working with RADIAL generation format
  center_x: 0
  center_z: 0
  # Coordinates when working with NEAR_<SOMETHING>
  # What can be the closest and farthest distance from the source object's location point
  min_near_point_distance: 30
  max_near_point_distance: 60
  # Maximum number of attempts to find a location for teleport (needed to avoid getting stuck in an infinite location search loop)
  max_location_attempts: 50
# Cooldown settings
cooldown:
  # Default cooldown for teleportation (-1 to disable)
  default_cooldown: 60
  # Teleportation cooldowns in seconds for each group (Set [] to disable group cooldowns entirely, -1 to disable cooldown for a group)
  group_cooldowns:
    vip: 30
    premium: 10
  # Pre-teleportation cooldown (-1 to disable)
  default_pre_teleport_cooldown: 5
  # Pre-teleportation cooldowns in seconds for each group (Set [] to disable group cooldowns entirely, -1 to disable cooldown for a group)
  pre_teleport_group_cooldowns:
    vip: 1
  # If the player's group is not in the list, the cooldown for the last group in the list will be used instead of the default
  use_last_group_cooldown: false
# Countdown bossbar settings
# Not active if pre-teleportation cooldown < 0
bossbar:
  # Is bossbar enabled
  enabled: true
  # Bossbar settings
  # Available bossbar colors: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
  # Available bossbar styles: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
  title: '&fTeleportation in: &5%time%'
  color: WHITE
  style: SEGMENTED_12
# Particle settings
particles:
  # Pre-teleport animation settings
  # Not active if pre-teleportation cooldown < 0
  pre_teleport:
    # Are particles enabled
    enabled: false
    # Should particles be sent only to the player who is teleporting?
    send_only_to_player: true
    # What particles will be in the animation
    # Will be in order
    id:
      - FLAME
    # How many initial reference points will there be for the animation
    dots: 2
    # At what distance from the player will particles appear
    radius: 1.25
    # How fast should particles scatter (0.0 for them to be static)
    particle_speed: 0.0
    # What will be the animation speed
    speed: 4.0
    # Should the animation be inverted
    # Counter-clockwise instead of clockwise and not top to bottom, but bottom to top (if jumping: false)
    invert: false
    # Should the animation be "jumping"
    jumping: true
    # Should the animation approach the player? (invert does not apply to this parameter)
    move_near: true
  # Post-teleport particle settings
  after_teleport:
    # Are particles enabled
    enabled: true
    # Should particles be sent only to the player who is teleporting?
    send_only_to_player: true
    # What particle will it be
    id: CLOUD
    # How many will there be
    count: 45
    # At what distance from the player will particles appear
    radius: 1.25
    # How fast should particles scatter (0.0 for them to be static)
    particle_speed: 0.0
# Restrictions imposed on the player before teleportation
# Not active if pre-teleportation cooldown < 0
restrictions:
  # Movement restriction before random teleport
  move: true
  # Teleportation restriction before random teleport (any teleport except plugins is considered)
  teleport: true
  # Damage restriction before random teleport
  damage: true
  # Restriction on dealing damage to other creatures
  damage_others: false
  # If this feature is enabled - damage check will only apply if damage was caused by one player to another
  damage_check_only_players: true
# Various teleportation exceptions
avoid:
  # Blocks on which the player cannot/can teleport
  # To disable the check - set list: []
  blocks:
    # Operation mode.
    # true - cannot teleport on these blocks false - can only teleport on these blocks
    blacklist: true
    list:
      - 'LAVA'
      - 'WATER'
  # Biomes in which the player cannot/can teleport
  # To disable the check - set list: []
  biomes:
    # Operation mode.
    # true - cannot teleport in these biomes false - can only teleport in these biomes
    blacklist: true
    list:
      - 'OCEAN'
  # Should player teleportation to WorldGuard regions be blocked
  regions: true
  # Should player teleportation to Towny towns be blocked
  towns: false
# Actions during teleportation
# Available actions:
# [MESSAGE] <message> - send a message to the player (supports PlaceholderAPI if enabled)
# [ACTIONBAR] <message> - send a message to the player in the action bar
# [SOUND] <id>;<volume>;<pitch> - send a sound to the player
# [TITLE] <title>;<subtitle>;<fade_in>;<stay>;<fade_out> - send a title to the player
# [EFFECT] <effect>;<duration>;<amplifier> - give an effect to the player
# [CONSOLE] <command> - execute a command from console
actions:
  # Hex format - &#IIIDDD
  # Available placeholders
  # %player% - player nickname
  # %name% - teleport channel name
  # %time% - time until teleportation
  # %x% %y% %z% - location coordinates
  # For [MESSAGE] hover text and click event are available. Specify via hoverText={Text-on-hover} and clickEvent={action-id;action-on-click}
  # Available actions for clickEvent: https://www.javadoc.io/static/net.kyori/adventure-api/4.17.0/net/kyori/adventure/text/event/ClickEvent.Action.html
  # Also for [MESSAGE] buttons are available. Created using button={Button-text;Action1;Action2}. Actions 1 and 2 are hoverText and clickEvent respectively.
  pre_teleport:
    - '[MESSAGE] &7&l(&5&lMSTRandomTeleport&7&l) &6» &fYou will be teleported in %time% Do not move or take damage. &6(Cancel RTP - /rtp cancel)'
    - '[SOUND] BLOCK_NOTE_BLOCK_PLING;1;1'
  on_cooldown:
    3:
      - '[TITLE] &aTeleport in &e3...;&r;5;50;10'
    2:
      - '[TITLE] &aTeleport in &62...;&r;5;50;10'
    1:
      - '[TITLE] &aTeleport in &c1...;&r;5;50;10'
  after_teleport:
    - '[MESSAGE] &7&l(&5&lMSTRandomTeleport&7&l) &6» &aSuccessful teleportation! &fYou teleported to coordinates: &2%x% %y% %z%.'
    - '[TITLE] &a&lSuccess!;&fYou teleported to coordinates: &2%x% %y% %z%.'
    - '[SOUND] ENTITY_PLAYER_LEVELUP;1;1'